export type ModuleTemplateInput = {
  slug: string;
  identifier: string;
  title: string;
};

function createFunctionName(title: string): string {
  return title.replaceAll(" ", "");
}

export function createTypesTemplate(
  input: ModuleTemplateInput,
): string {
  return `export type ${input.identifier}ModuleInput = {
  action: string;
};

export type ${input.identifier}ModuleResult = {
  success: boolean;
  message: string;
};
`;
}

export function createConfigTemplate(
  input: ModuleTemplateInput,
): string {
  return `export const ${input.identifier}ModuleConfig = {
  name: "${input.slug}",
  title: "${input.title}",
  enabled: true,
  version: "0.1.0",
  maturity: "Seed",
} as const;
`;
}

export function createValidatorTemplate(
  input: ModuleTemplateInput,
): string {
  const functionName = createFunctionName(input.title);

  return `import type { ${input.identifier}ModuleInput } from "./types";

export function validate${functionName}Input(
  input: ${input.identifier}ModuleInput,
): string[] {
  const errors: string[] = [];

  if (!input.action.trim()) {
    errors.push("Action is required.");
  }

  return errors;
}
`;
}

export function createTemplatesTemplate(): string {
  return `export function createModuleDocument(
  title: string,
): string {
  return \`# \${title}

Generated by HOLY ARC.
\`;
}
`;
}

export function createServiceTemplate(
  input: ModuleTemplateInput,
): string {
  const functionName = createFunctionName(input.title);
  const typeName = `${input.identifier}Module`;
  const eventName = `${input.slug
    .toUpperCase()
    .replaceAll("-", "_")}_ACTION`;

  return `import { writeAuditEvent } from "../../infrastructure/logging";
import type {
  ${typeName}Input,
  ${typeName}Result,
} from "./types";

export function execute${functionName}(
  input: ${typeName}Input,
): ${typeName}Result {
  writeAuditEvent({
    event: "${eventName}",
    module: "${input.slug}",
    status: "INFO",
    metadata: {
      action: input.action,
    },
  });

  return {
    success: true,
    message: "${input.title} action completed.",
  };
}
`;
}

export function createCommandTemplate(
  input: ModuleTemplateInput,
): string {
  const functionName = createFunctionName(input.title);

  return `import { execute${functionName} } from "./service";

export function run${functionName}Command(
  args: string[],
): void {
  const action = args[0]?.trim();

  if (!action) {
    console.error("Usage: arc ${input.slug} <action>");
    process.exitCode = 1;
    return;
  }

  try {
    const result = execute${functionName}({
      action,
    });

    console.log(result.message);
  } catch (error) {
    const message =
      error instanceof Error
        ? error.message
        : "Unknown ${input.title} module error.";

    console.error(message);
    process.exitCode = 1;
  }
}
`;
}

export function createIndexTemplate(
  input: ModuleTemplateInput,
): string {
  const functionName = createFunctionName(input.title);

  return `export { run${functionName}Command } from "./command";
export { execute${functionName} } from "./service";
export type {
  ${input.identifier}ModuleInput,
  ${input.identifier}ModuleResult,
} from "./types";
`;
}

export function createLoggerTemplate(): string {
  return `export {
  writeAuditEvent,
} from "../../infrastructure/logging";
`;
}

export function createModuleTemplate(
  input: ModuleTemplateInput,
): string {
  return `# ${input.title} Module

Status: Development  
Version: 0.1.0  
Maturity: Seed  
Classification: HOLY ARC Platform Module

---

## Mission

Define the mission of the ${input.title} module.

---

## Primary Responsibility

Define the single responsibility owned by this module.

---

## Not Responsible For

- Responsibilities owned by another HOLY ARC module
- Shared infrastructure already provided by the platform
- Product-specific experience logic
- Unapproved execution outside platform governance

---

## Dependencies

- Configuration
- Filesystem
- Logging
- Workspace
- Shared validation
- Shared IDs

---

## Provides

Define the capabilities, contracts, events, and outputs provided by this module.

---

## Multiplier

| Dimension | Current | Target | Evidence |
|---|---:|---:|---|
| Reuse | 0/10 | 8/10 | Used by multiple modules or experiences |
| Speed | 0/10 | 8/10 | Reduced execution or development time |
| Safety | 0/10 | 8/10 | Reduced errors, exposure, or operational risk |
| Knowledge | 0/10 | 8/10 | Preserved reusable learning and evidence |
| Scale | 0/10 | 8/10 | Supports more clients, products, or users |

### Current Multiplier Score

0.0 / 10

### Target Multiplier Score

8.0 / 10

### Expected Future Capability

Describe how completing this module will make later ARC work easier, faster, safer, more reusable, or more valuable.

### Evidence Required

- [ ] Used by another module
- [ ] Used by an experience or client solution
- [ ] Reduced repeated manual work
- [ ] Measurable time saved
- [ ] Reduced failure or error rate
- [ ] Produced reusable knowledge
- [ ] Supported increased operating scale

### Review Date

Not scheduled.

---

## Maturity Model

| Level | Meaning |
|---|---|
| Seed | Module structure exists |
| Growing | Core capability is being implemented |
| Stable | Tested and ready for normal use |
| Platform | Reused by multiple modules or experiences |
| Foundational | Critical infrastructure used throughout HOLY ARC |

### Current Maturity

Seed

### Promotion Requirements

To become Growing:

- Primary responsibility is locked
- Core service is implemented
- Validation exists
- Audit events exist
- Initial tests pass

To become Stable:

- Main workflows are complete
- Failure paths are tested
- Documentation is accurate
- Multiplier evidence has begun
- No unresolved critical defects

To become Platform:

- Reused by multiple modules or experiences
- Interfaces are stable
- Duplicate capability has been removed elsewhere
- Multiplier improvement is measurable

To become Foundational:

- Used throughout HOLY ARC
- Failure would materially affect the platform
- Governance and recovery controls exist
- Architecture and contracts are formally locked

---

## Lifecycle

Intent  
↓  
Command  
↓  
Validation  
↓  
Service  
↓  
Logging  
↓  
Knowledge  
↓  
Multiplier  
↓  
Result  
↓  
Feedback

---

## Contracts

### Inputs

Define accepted input contracts.

### Outputs

Define returned results and generated artifacts.

### Events

Define emitted audit or platform events.

### Errors

Define expected failure conditions.

---

## Engineering Rules

1. Own one primary responsibility.
2. Do not assume responsibilities owned by another HOLY ARC module.
3. Reuse shared infrastructure instead of duplicating it.
4. Increase the long-term multiplier of future work.
5. Support multiplier claims with evidence.
6. Keep platform logic separate from experience logic.
7. Record meaningful actions through audit events.
8. Preserve feedback so the module can improve from reality.

---

## Success Criteria

- Responsibility is clear
- Inputs are validated
- Outputs are predictable
- Audit evidence is recorded
- Tests pass
- Documentation matches implementation
- Multiplier evidence exists
- Future work becomes easier because this module exists

---

## Roadmap

### Seed

- Lock responsibility
- Define contracts
- Create baseline tests

### Growing

- Implement core workflows
- Add failure handling
- Add audit coverage

### Stable

- Complete testing
- Validate documentation
- Measure multiplier

### Platform

- Reuse across modules and experiences
- Stabilise interfaces
- Remove duplicated capability

### Foundational

- Add governance
- Add recovery controls
- Lock architecture
`;
}

export function createReadmeTemplate(
  input: ModuleTemplateInput,
): string {
  return `# ${input.title} Module Developer Guide

The constitutional identity of this module is defined in:

- [MODULE.md](./MODULE.md)

## Command

\`\`\`powershell
arc ${input.slug} <action>
\`\`\`

## Files

- MODULE.md — architecture, responsibility, multiplier and maturity
- command.ts — CLI interaction
- service.ts — business logic
- validator.ts — input validation
- templates.ts — generated content
- logger.ts — audit access
- config.ts — module configuration
- types.ts — data contracts
- tests — automated proof

## Development Rule

Update MODULE.md whenever responsibility, contracts, maturity, dependencies or multiplier expectations change.
`;
}

export function createTestTemplate(
  input: ModuleTemplateInput,
): string {
  const functionName = createFunctionName(input.title);

  return `import assert from "node:assert/strict";
import test from "node:test";
import { execute${functionName} } from "../service";

test("${input.slug} module returns a successful result", () => {
  const result = execute${functionName}({
    action: "test",
  });

  assert.equal(result.success, true);
});
`;
}